 
package main
 
import (
    "fmt"
    "os"
)
 
func Foo() error {
    var err *os.PathError = nil
    return err
}
 
func main() {
    err := Foo()
    fmt.Println(err)
    fmt.Println(err == nil)

}

Ответ: программа выводит <nil> false. Это происходит из-за того, что мы ссылаемся на переменную типа os.PathError, но то, что мы возвращаем - сложная структура, которая несет в себе информацию о типе переменной, адрес в памяти на блок, в котором лежит nil указатель. При этом если бы мы взяли пустой интерфейс, то он был бы равен nil, так как все поля были бы пустые.